---
title: "Multilevel Regression and Poststratification Based Norming"
---

## Project Abstract
By itself, a raw score on a psychological test or measure has little meaning. Usually, individual scores can only be interpreted meaningfully when they are compared against a given reference population - a norm. Good test norms are important for accurate individual diagnostics, identifying sampling bias, and calculating standardised effect sizes that can be compared across studies. Traditionally, norms are constructed from random, representative samples from the population. However, it is becoming increasingly difficult to reach representative samples, as nonresponse soars and traditional sampling methods like random digit dialling fail. Outside of psychology, Multilevel Regression and Poststratification (MRP) is one of the most widely used methods to correct for nonrepresentative sampling. We argue that many areas of psychology research would greatly benefit from adopting MRP, and therefore provide this tutorial. MRP involves fitting a mixed-effects model to a large and diverse sample and weighting predicted scores by true population values (sourced from census data, for example). Using IQ test data from the TwinLife study (N = 10,059, Culture Fair Test, CFT 20-R) as an example, we show that MRP has the potential to make good test norms more accessible to psychologists by substantially reducing costs of sampling across a wide range of domains.

## Reproducibility

4 things are required to be able to rerun the code here:

1. TwinLife data: versions 2 and 6 of the dataset have to be requested from [GESIS](https://search.gesis.org/research_data/ZA6701). Alternatively you can run the tutorial code on the synthetic sample we provide on our [OSF project](https://osf.io/2r9sy/).
2. [CFT 20-R, German version norms](https://www.testzentrale.de/shop/grundintelligenztest-skala-2-revision-cft-20-r-mit-wortschatztest-ws-und-zahlenfolgentest-zf-revision-ws-zf-r-90116.html): Means and SDs (Streuung) of "Teil-1 Max" have to be manually extracted from the manual for age groups 11;1-11;6 through 60-64.
3. The census tables, which we provide on our [OSF project](https://osf.io/2r9sy/).
4. To ensure the code works as expected, it's best to have the same versions of R and the packages we use. This can be easily arranged by using the renv.lock file found in the main RProject folder to download the exact versions of the packages we used. Note that extra effort is needed to get _brms_ to work on your machine. Here is a [walk-through](https://learnb4ss.github.io/learnB4SS/articles/install-brms.html).