---
title: "Find brm to use in the final analysis"
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 3
    toc_float: true
---

# set up

```{r setup, message = FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = TRUE,
	include = TRUE,
	error = TRUE
)
```


# 18
## run brms
```{r}
library(tidybayes)
library(kableExtra)
library(ggrepel)
library(marginaleffects)
library(tidyverse)
library(brms)

theme_set(theme_gray(base_size = 14))

census_school_type <- readxl::read_excel("../data/729305_Zensus2011_Bildung_Schulform.xlsx", 
    sheet = "Migration und Schulform") 

census_school_type <- census_school_type %>% 
  # remove redundant columns of higher at school categories (e.g., Deutsche mit Migrationshintergrund)
  select(1:2, 21:28, 45:60, 69:76, 85:100) %>%
  # exclude sex and age columns
  select(3:50) %>%
  # before iteratively naming the 48 columns, 8 (school types) * 6 (migration background) 
  set_names(map(c("no mig background", 
                  "foreigner, own mig background", 
                  "foreigner, no own mig background", 
                  "citizen, own mig background",
                  "citizen, mig background from both parents",
                  "citizen, mig background from one parent"),
                ~ paste0(.x, "_", c("total", 
                                    "no longer at school", # Entfällt, da kein/e Schüler/-innen
                                    "at school: primary", # Grundschule
                                    "at school: lower secondary", # Hauptschule
                                    "at school: intermediate secondary", # Realschule
                                    "at school: upper secondary", # Gymnasium
                                    "at school: comprehensive school", # Gesamtschule
                                    "at school: other school"))) %>% # Sonstige Schule
            unlist()) %>%
  mutate(age = as.numeric(parse_number(census_school_type[[2]])),
         male = census_school_type[[1]],
         ) %>% 
  relocate(c(age,male)) %>% 
  mutate(male = ifelse(row_number() >= 115 & row_number() <= 215, TRUE, FALSE)) %>% 
  slice(-(1:113), -215) %>% 
  pivot_longer(cols = 3:50,
               names_to = c("mig", "school_type"),
               names_sep = "_",
               values_to = "census_n") %>%
  mutate(census_n = ifelse(census_n == "/", 0, as.numeric(census_n)))



census_ISCED <- readxl::read_excel("../data/729305_Zensus2011_Bildung_ISCED.xlsx", sheet = "Migration und ISCED")

census_ISCED <- census_ISCED %>% 
  set_names(paste0("var", 1:133)) %>% 
  select(-(
    census_ISCED %>% 
    summarise(across(everything(), ~ any(str_detect(., "ISCED-Ebene")) & any(str_detect(., "Insgesamt")))) %>% 
    unlist() %>% 
    which()
  )) %>% 
  select(1:2, var24:var34, var57:var78, var90:var100, var112:var133) %>% 
  select(3:56) %>%
  set_names(map(c("no mig background", 
                  "foreigner, own mig background", 
                  "foreigner, no own mig background", 
                  "citizen, own mig background",
                  "citizen, mig background from both parents",
                  "citizen, mig background from one parent"),
                ~ paste0(.x, "_", c("total",
                                    "isced 1: primary",                                
                                    "isced 2a: lower secondary",                             
                                    "isced 3a: upper secondary, general",                               
                                    "isced 3b: upper secondary, vocational",                               
                                    "isced 4a: post-secondary",                               
                                    "isced 5a: tertiary, college etc.",                               
                                    "isced 5b: tertiary, tech school etc.",                               
                                    "isced 6: PhD"))) %>% 
            unlist()) %>% 
  mutate(age = as.numeric(parse_number(census_ISCED[[2]])),
         male = census_ISCED[[1]]) %>% 
  relocate(c(age,male)) %>% 
  mutate(male = ifelse(row_number() >= 99 & row_number() <= 186, TRUE, FALSE)) %>% 
  slice(-(1:99), -186) %>% 
  pivot_longer(cols = 3:56,
               names_to = c("mig", "isced"),
               names_sep = "_",
               values_to = "census_n") %>%
  mutate(census_n = ifelse(census_n == "/", 0, as.numeric(census_n)))


# 11 because that's the minimum age for the educ and mig variables we used
census_school_type_11_18 <- census_school_type %>% 
  filter((age >= 11 & age <= 18) & school_type != "total") %>% 
  rename(educ = "school_type") %>% 
  relocate(educ, .after = "mig")


census_ISCED_19_79 <- census_ISCED %>% 
  filter((age >= 19 & age <= 79) & isced != "total") %>% 
  rename(educ = "isced")

census18 <- census_school_type_11_18 %>% 
  bind_rows(census_ISCED_19_79) %>%
  mutate(over_18 = ifelse(age > 18, T, F))


library(tidyverse)
library(brms)
options(mc.cores = 4, 
        brms.backend = "cmdstanr",
        scipen = 999,
        digits = 4)

load("../data/tl_clean.Rda")
tl_no_1st_twins18 <- tlperson  %>% 
  filter(ptyp == 300 | ptyp == 400) %>% 
  pivot_wider(id_cols = fid, names_from = ptyp, values_from = mig2000) %>% 
  right_join(tlperson, by = "fid") %>% 
  rename(mig2000_dad = `400`, mig2000_mom = `300`) %>% 
  mutate(cft = igf0182 + igf0282 + igf0382 + igf0482,
         age = age0101/12,
         male = sex == 1,
         mig2000_dad = as.numeric(ifelse(ptyp == 300 | ptyp == 400, NA_character_, mig2000_dad)),
         mig2000_mom = as.numeric(ifelse(ptyp == 300 | ptyp == 400, NA_character_, mig2000_mom)),
         mig0300 = recode(as.numeric(mig0300), `2` = 1),
         mig0400 = recode(as.numeric(mig0400), `2` = 1),
         mig0520 = coalesce(mig0520, 1),

         eca0108 = str_sub(as.character(as_factor(eca0108)), 4, -1),
         born_abroad = case_when(
            mig2000 != 1 ~ 'self',
            mig2000 == 1 & ((coalesce(mig2000_dad, mig0400) == 1 & coalesce(mig2000_mom, mig0300) == 1)) ~ 'none',
            coalesce(mig2000_dad, mig0400) != 1 & coalesce(mig2000_mom, mig0300) != 1 ~ 'both_parents',
            mig2000_mom != 1 ~ 'one_parent',
            mig2000_dad != 1 ~ 'one_parent',  
            mig0300 != 1 ~ 'one_parent',
            mig0400 != 1 ~ 'one_parent',
            mig2000 == 1 ~ 'none',
            TRUE ~ "none"), 
         mig = case_when(
            born_abroad == "self" & mig0520 == 1 ~ "citizen, own mig background",
            born_abroad == "self" & mig0520 != 1 ~ "foreigner, own mig background",
            born_abroad != "self" & mig0520 != 1 ~ "foreigner, no own mig background",
            born_abroad == "one_parent" & mig0520 == 1 ~ "citizen, mig background from one parent",
            born_abroad == "both_parents" & mig0520 == 1 ~ "citizen, mig background from both parents",
            born_abroad == "none" & mig0520 == 1 ~ "no mig background"),
         school_type = case_when(
            edu0400 == 1 ~ "at school: primary", # Grundschule
            edu0400 == 2 ~ "at school: primary", # Orientierungsschule
            edu0400 == 3 ~ "at school: lower secondary", # Hauptschule
            edu0400 == 4 ~ "at school: intermediate secondary", # Realschule
            edu0400 == 5 ~ "at school: comprehensive school", # Verbundene Haupt- und Realschule (auch Sekundar-, Real-, Regel-, Mittel-, Ober- und Wirtschaftsschule, regionale Schule, erweiterte Realschule)
            edu0400 == 6 ~ "at school: comprehensive school", # Gesamtschule
            edu0400 == 7 ~ "at school: comprehensive school", # Waldorfschule
            edu0400 == 8 ~ "at school: upper secondary", # Gymnasium (auch Kolleg)
            edu0400 == 9 ~ "at school: other school", # Sonderschule/Förderschule
            edu0400 == 10 ~ "at school: other school", # Andere Schule
            edu0100 == 3 ~ "no longer at school")) %>%  # "ich gehe nicht mehr in die Schule"
  mutate(isced = case_when(
            eca0108 == "3] -83: in school or training/not in school yet" ~ "isced 1: primary",
            eca0108 == "9] -89: not codable" ~ NA_character_,
            eca0108 == "5] -95: doesn't apply (screened out)" ~ NA_character_,
            eca0108 == "level 1" ~   "isced 1: primary",
            eca0108 == "level 2a" ~  "isced 2a: lower secondary",
            eca0108 == "level 3a" ~  "isced 3a: upper secondary, general",
            eca0108 == "level 3b" ~  "isced 3b: upper secondary, vocational",
            eca0108 == "level 3c" ~  "isced 3b: upper secondary, vocational",
            eca0108 == "level 4a" ~  "isced 4a: post-secondary",
            eca0108 == "level 5a" ~  "isced 5a: tertiary, college etc.",
            eca0108 == " level 5b" ~ "isced 5b: tertiary, tech school etc.",
            eca0108 == " level 6" ~  "isced 6: PhD"),
         educ = as.factor(ifelse(age0100 <= 18, school_type, isced)),
         educ = relevel(educ, 10),
         isced = relevel(as.factor(isced), 4)) %>%
 filter(!is.na(cft)
        & !is.na(educ)  
        & ptyp != 1)

brm_age_by_educ_18_delta_99 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 5000,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.99),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_delta_99_5000",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_delta_98 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 5000,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.98),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_delta_98",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")

brm_age_by_educ_18_intercept_prior2 <-
  brm(bf(
      cft_total ~ 0 + Intercept + (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ 0 + Intercept + (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      prior = c(
                set_prior("student_t(3, 38, 1)", class = "Intercept")),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_intercept_prior2",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_delta_975 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 4000,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.975),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_delta_975_4000",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_delta_975 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 3000,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.975),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_delta_975_3000",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_b_prior <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      prior = c(set_prior("normal(0, 1)", class = "b")),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_b_prior",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")




brm_age_by_educ_18_intercept_prior <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      prior = c(
                set_prior("student_t(3, 38, 1)", class = "Intercept")),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_intercept_prior",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_spline_priors <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      prior = c(set_prior("student_t(3, 0, 9)", class = "sds", coef = "s(age, by = educ)"),
                set_prior("normal(0, 1)", class = "b"),
                set_prior("student_t(3, 38, 1)", class = "Intercept")),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_spline_priors",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_delta_975 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2750,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.975),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_delta_975",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_delta_975 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2750,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.975),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_delta_975",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")



brm_age_by_educ_18_delta_95 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2500,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.95),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_delta_95",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")



brm_age_by_educ_18_fs <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ, bs = "fs"),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, bs = "fs")),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_releveled_fs",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")




brm_age_by_educ_18 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_releveled",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_delta_90 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.90),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_delta_90",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_isced <-
  brm(bf(
      cft_total ~ (1 + age | mig)  + (male)  + (1 | mig:male) + (1 | mig:isced) + (1 | male:isced) + (1 | mig:isced:male) + s(age, by = isced),
      sigma ~ (1 | mig) + (1 | isced) + (male)  + (1 | mig:male) + (1 | mig:isced) + (1 | male:isced) + (1 | mig:isced:male) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_isced_releveled",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_delta_85 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 3000,
      family = gaussian(),
      seed = 810,
      control = list(adapt_delta = 0.85),
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_18_releveled",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_educ_18 <-
  brm(bf(
      cft_total ~ (1 + age | mig) + (1 + age | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age),
      sigma ~ (1 | mig) + (1 | educ) + (male)  + (1 | mig:male) + (1 | mig:educ) + (1 | male:educ) + (1 | mig:educ:male) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_educ_new_18",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")


brm_age_by_educ_18_delta_975
brm_age_by_educ_18
brm_age_by_educ_18_spline_priors 

plot(conditional_effects(brm_age_by_educ_18_delta_975), points = T)

brm_age_by_educ_18_intercept_prior 
brm_age_by_educ_18_b_prior 

loo_compare(brm_age_by_educ_18_b_prior, brm_age_by_educ_18_delta_975, brm_age_by_educ_18_delta_95, brm_age_by_educ_18_delta_90, brm_age_by_educ_18_fs, brm_age_by_educ_18_releveled, brm_age_by_educ_over_18, brm_age_by_educ_over_18_in_by)

brm_age_by_educ_18_delta_98 
```


# pp checking
```{r}
ppc1 <- brm(bf(
      cft_total ~ s(age, by = educ)),
      chains = 4,
      family = gaussian(),
      sample_prior = "only",
      prior = c(set_prior("student_t(3, 0, 8.9)", class = "sds", coef = "s(age, by = educ)"),
                set_prior("normal(0,20)", class = "b")),
      seed = 810,
      data = tl_no_1st_twins18)



conditional_effects(ppc1, conditions = data.frame(educ = c("isced 3b: upper secondary, vocational", "no longer at school")))

ppc_plot <- conditional_effects(ppc)
str(ppc_plot[[1]])
plot(ppc_plot)[[1]] +
  facet_wrap("educ")


get_prior(cft_total ~ s(age, by = educ), data = tl_no_1st_twins18)
```

```{r}
ppc2 <- brm(bf(
      cft_total ~ s(age, by = educ)),
      chains = 4,
      family = gaussian(),
      sample_prior = "only",
      prior = c(set_prior("student_t(3, 0, 1)", class = "sds", coef = "s(age, by = educ)"),
                set_prior("normal(0,20)", class = "b")),
      seed = 810,
      data = tl_no_1st_twins18)



conditional_effects(ppc2, conditions = data.frame(educ = c("isced 3b: upper secondary, vocational", "no longer at school")))
```

```{r}
ppc3 <- brm(bf(
      cft_total ~ s(age, by = educ)),
      chains = 4,
      family = gaussian(),
      sample_prior = "only",
      prior = c(set_prior("student_t(3, 0, 100)", class = "sds", coef = "s(age, by = educ)"),
                set_prior("normal(0,20)", class = "b")),
      seed = 810,
      data = tl_no_1st_twins18)



conditional_effects(ppc3, conditions = data.frame(educ = c("isced 3b: upper secondary, vocational", "no longer at school")))
```

```{r}
ppc4 <- brm(bf(
      cft_total ~ s(age, by = educ)),
      chains = 4,
      family = gaussian(),
      sample_prior = "only",
      prior = c(set_prior("student_t(3, 0, 0.1)", class = "sds", coef = "s(age, by = educ)"),
                set_prior("normal(0,0.1)", class = "b")),
      seed = 810,
      data = tl_no_1st_twins18)



conditional_effects(ppc4, conditions = data.frame(educ = c("isced 3b: upper secondary, vocational", "no longer at school")))
```



```{r}
ppc5 <- brm(bf(
      cft_total ~ s(age, by = educ)),
      chains = 4,
      family = gaussian(),
      sample_prior = "only",
      prior = c(set_prior("student_t(3, 0, 0.1)", class = "sds", coef = "s(age, by = educ)"),
                set_prior("normal(0,0.1)", class = "b"),
                set_prior("student_t(3, 38, 0.1)", class = "Intercept")),
      seed = 810,
      data = tl_no_1st_twins18)



conditional_effects(ppc5, conditions = data.frame(educ = c("isced 3b: upper secondary, vocational", "no longer at school")))
```




## spline by educ in mgcv
```{r}
library(mgcv)
plot(gam(cft_total ~ s(age, by = educ), data = tl_no_1st_twins18))
```

```{r}
library(mgcv)
plot(gam(cft_total ~ s(age, by = educ, bs = "fs"), data = tl_no_1st_twins18))
```



# loo compare
```{r}
loo_compare(brm_age_by_educ_18,  brm_educ_18) %>% kable() %>% kable_styling(full_width = F)
```


## MRPs
```{r}

mrp_age_norms <- function(ps_table, ps_variables, brm) {

  norming_sample <- brm$data
  sim_sample <- ps_table %>% 
    sample_n(size = 100000, weight = census_n, replace = TRUE) %>% 
    select(all_of(ps_variables))
  
  sim_sample_with_draws <- sim_sample %>%
    add_predicted_draws(brm, ndraws = 1000, seed = 810, 
                        allow_new_levels = TRUE) %>% 
    mutate(.prediction = case_when(.prediction < 0 ~ 0,
                                   .prediction > 56 ~ 56,
                                   TRUE ~ .prediction))
  

  
  means_sds_and_ses <- sim_sample_with_draws %>%
    group_by(age, .draw) %>% 
    summarise(mean_prediction = mean(.prediction), sd_prediction = sd(.prediction)) %>%
    summarise(mrp_mean = mean(mean_prediction), 
              mrp_seOfmean = sd(mean_prediction), 
              mrp_sd = sqrt(mean(sd_prediction^2)), 
              mrp_seOfsd = sd(sd_prediction))
  
  norm_sample_with_draws <- norming_sample %>% 
    select(all_of(ps_variables)) %>% 
    add_predicted_draws(brm, ndraws = 1000, seed = 810, allow_new_levels = TRUE) %>%
    mutate(.prediction = case_when(.prediction < 0 ~ 0,
                                   .prediction > 56 ~ 56,
                                   TRUE ~ .prediction)) 
  
  means_sds_and_ses_no_ps <- norm_sample_with_draws %>%
    mutate(age = floor(age)) %>%
    group_by(age, .draw) %>% 
    summarise(mean_prediction = mean(.prediction), sd_prediction = sd(.prediction)) %>%
    summarise(mr_mean = mean(mean_prediction), mr_seOfmean = sd(mean_prediction), mr_sd = sqrt(mean(sd_prediction^2)), mr_seOfsd = sd(sd_prediction))
  
  tl_summary <- norming_sample %>% 
    mutate(age = floor(age)) %>% 
    group_by(age) %>% 
    summarise(tl_n = n(), tl_mean = mean(cft_total, na.rm = TRUE), tl_sd = sd(cft_total, na.rm = TRUE), tl_seOfmean = tl_sd/sqrt(tl_n))
  
  big_table <- ps_table  %>% 
    group_by(age) %>% 
    summarise(census_n = sum(census_n)) %>% 
    left_join(means_sds_and_ses, by = c("age"))  %>%
    left_join(means_sds_and_ses_no_ps, by = c("age")) %>% 
    left_join(tl_summary, by = "age") %>% 
    mutate(abs_dif = abs(mrp_mean - tl_mean))
  
  big_table_long <- big_table %>% 
    filter(age <= 60) %>% 
    pivot_longer(-age, names_to = c("source", ".value"), names_pattern = "(.*)_(.*)") %>% 
    filter(source != "census" 
           & source != "abs"
          )
  
  plot1 <- ggplot(data = big_table_long, aes(x = as.factor(age), y = mean, group = source, colour = source)) +
    geom_line(linewidth = 1) +
    geom_point(size = 3, shape = 18, position = position_dodge(width = 0.3)) +
    geom_errorbar(size = 1, aes(ymin = mean - 1.96 * seOfmean, ymax = mean + 1.96 * seOfmean), width = 0.5, position = position_dodge(width = 0.7)) +
    scale_x_discrete(breaks = seq(11, 79, by = 2)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major.x = element_line(color = "gray", linetype = "dashed"),
        panel.grid.minor.x = element_blank()) +
  guides(colour = guide_legend(override.aes = list(size = 2)))  # Adjust the size of the legend

  
  plot2 <- ggplot(data = big_table_long, aes(x = as.factor(age), y = sd, group = source, colour = source)) +
    geom_line(linewidth = 1) +
    geom_point(size = 3, shape = 18) +
    scale_x_discrete(breaks = seq(11, 79, by = 2)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  plot3 <- ggplot(data = big_table_long, aes(x = as.factor(age), y = seOfmean, group = source, colour = source)) +
    geom_line(linewidth = 1) +
    geom_point(size = 3, shape = 18) +
    scale_x_discrete(breaks = seq(11, 79, by = 2)) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  t_test_result <- t.test(big_table$tl_mean, big_table$mrp_mean)
  
  mrp_overall_estimates <- sim_sample_with_draws %>%
    group_by(.draw) %>% 
    summarise(mean_prediction = mean(.prediction), sd_prediction = sd(.prediction)) %>%
    summarise(mrp_mean = mean(mean_prediction), 
              mrp_seOfmean = sd(mean_prediction), 
              mrp_sd = sqrt(mean(sd_prediction^2)), 
              mrp_seOfsd = sd(sd_prediction))
  
  average_abs_diff <- mean(big_table$abs_dif, na.rm=T)
  abs_diff_11_30 <- big_table %>% filter(age >= 11 & age <= 30) %>% select(age, abs_dif)
  
  return(list(
    plot1 = plot1,
    plot2 = plot2,
    plot3 = plot3,
    t_test_result = t_test_result,
    mrp_overall_estimates = mrp_overall_estimates,
    average_abs_diff = average_abs_diff,
    abs_diff_11_30 = abs_diff_11_30
  ))
}



```

### brm_age_by_educ_18
```{r, fig.width=11}
brm_age_by_educ_18
mrp_age_norms(ps_table = census18, 
              ps_variables = c("age", "educ", "mig", "male"),
              brm = brm_age_by_educ_18_delta_98)


brm_age_by_educ_18_delta_99$data %>% group_by(educ) %>% summarise(n()) %>% View

tl_no_1st_twins18 %>% group_by(educ) %>% summarise(n()) %>% View

mcmc_plot(brm_age_by_educ_18_delta_99, type = "trace")
plot(brm_age_by_educ_18_delta_99)
```

```{r}
PD_matrix <- fitted(brm_age_by_educ_18, newdata = census18, seed = 810, allow_new_levels = T, summary = T)

tl_summary <- tl_no_1st_twins18 %>% 
  mutate(age = floor(age)) %>% 
  group_by(age) %>% 
  summarise (tl_n = n(), tl_mean = mean(cft_total, na.rm = T), tl_sd = sd(cft_total, na.rm = T), tl_seOfmean = tl_sd/sqrt(tl_n))

census18 %>% 
  bind_cols(PD_matrix) %>%
  group_by(age) %>% 
  summarise(mrp_mean = sum(Estimate*census_n)/sum(census_n)) %>%
  left_join(select(tl_summary, c(age, tl_mean)), by = "age") %>% 
  mutate(abs_dif = abs(mrp_mean - tl_mean)) %>% 
  filter(age >= 16 & age <= 25)
```




### brm_educ_18
```{r, fig.width=11}
brm_educ_18
mrp_age_norms(ps_table = census18, 
              ps_variables = c("mig", "age", "educ", "male"),
              brm = brm_educ_18)
```





# separate Ps


```{r, fig.width=11}

census_school_type_11_21 <- census_school_type %>% 
  filter((age >= 11 & age <= 21) & school_type != "total") %>% 
  mutate(census_n = case_when(is.na(census_n) ~ 0,
                            TRUE ~ census_n))


census_ISCED_19_79 <- census_ISCED %>% 
  filter((age >= 19 & age <= 79) & isced != "total") %>% 
  mutate(census_n = case_when(is.na(census_n) ~ 0,
                            TRUE ~ census_n))

brm_ST_linear <-
  brm(bf(
      cft_total ~ (1 + age | mig) + (1 + age | school_type) + (male)  + (1 | mig:male) + (1 | mig:school_type) + (1 | male:school_type) + (1 | mig:school_type:male) + (age),
      sigma ~ (1 | mig) + (1 | school_type) + (male)  + (1 | mig:male) + (1 | mig:school_type) + (1 | male:school_type) + (1 | mig:school_type:male) + (age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_ST_linear_new",
      file_refit = "never",
      data = tl_no_1st_twins_11_21) %>% 
  add_criterion("loo")



sim_sample <- census_school_type_11_21 %>% 
  sample_n(size = 100000, weight = census_n, replace = TRUE) %>% 
  select(age, mig, school_type, male)


sim_sample_with_draws <- sim_sample %>%
  add_predicted_draws(brm_ST_linear, ndraws = 1000, seed = 810, allow_new_levels = T) %>% 
  mutate(.prediction = case_when(.prediction < 0 ~ 0, # censor predictions which go over scale limits
                                 .prediction > 56 ~ 56,
                                 TRUE ~ .prediction))


means_sds_and_ses_ST <- sim_sample_with_draws %>%
  group_by(age, .draw) %>% 
  summarise(mean_prediction = mean(.prediction), sd_prediction = sd(.prediction)) %>%
  summarise(mrpST_mean = mean(mean_prediction), 
            mrpST_seOfmean = sd(mean_prediction), 
            mrpST_sd = sqrt(mean(sd_prediction^2)), 
            mrpST_seOfsd = sd(sd_prediction))

sim_sample <- census_ISCED_19_79 %>% 
  sample_n(size = 100000, weight = census_n, replace = TRUE) %>% 
  select(age, mig, isced, male)


sim_sample_with_draws <- sim_sample %>%
  add_predicted_draws(brm_age_by_isced, ndraws = 1000, seed = 810, allow_new_levels = T) %>% 
  mutate(.prediction = case_when(.prediction < 0 ~ 0, # censor predictions which go over scale limits
                                 .prediction > 56 ~ 56,
                                 TRUE ~ .prediction))


means_sds_and_ses_ISCED <- sim_sample_with_draws %>%
  group_by(age, .draw) %>% 
  summarise(mean_prediction = mean(.prediction), sd_prediction = sd(.prediction)) %>%
  summarise(mrpISCED_mean = mean(mean_prediction), 
            mrpISCED_seOfmean = sd(mean_prediction), 
            mrpISCED_sd = sqrt(mean(sd_prediction^2)), 
            mrpISCED_seOfsd = sd(sd_prediction))

sim_sample <- census18 %>% 
  sample_n(size = 100000, weight = census_n, replace = TRUE) %>% 
  select(age, mig, educ, male)


sim_sample_with_draws <- sim_sample %>%
  add_predicted_draws(brm_age_by_educ_18, ndraws = 1000, seed = 810, allow_new_levels = T) %>% 
  mutate(.prediction = case_when(.prediction < 0 ~ 0, # censor predictions which go over scale limits
                                 .prediction > 56 ~ 56,
                                 TRUE ~ .prediction))


means_sds_and_ses_Educ <- sim_sample_with_draws %>%
  group_by(age, .draw) %>% 
  summarise(mean_prediction = mean(.prediction), sd_prediction = sd(.prediction)) %>%
  summarise(mrpEduc_mean = mean(mean_prediction), 
            mrpEduc_seOfmean = sd(mean_prediction), 
            mrpEduc_sd = sqrt(mean(sd_prediction^2)), 
            mrpEduc_seOfsd = sd(sd_prediction))


big_table <- means_sds_and_ses_Educ %>% 
  left_join(means_sds_and_ses_ISCED, by = c("age")) %>% 
  left_join(means_sds_and_ses_ST, by = c("age")) 

big_table_long <- big_table %>% 
  filter(age <= 60) %>% 
  pivot_longer(-age, names_to = c("provenance", ".value"), names_pattern = "(.*)_(.*)") 

ggplot(data = big_table_long, aes(x = as.factor(age), y = mean, group = provenance, colour = provenance)) +
  geom_line(linewidth = 1) +
  geom_point(size = 4, shape = 18, position = position_dodge(width = 0.7)) +
  geom_errorbar(size = 1, aes(ymin = mean - 1.96*seOfmean, ymax = mean + 1.96*seOfmean), width = .5, position = position_dodge(width = 0.3)) + scale_x_discrete(breaks = seq(11, 79, by = 2))
ggplot(data = big_table_long, aes(x = as.factor(age), y = sd, group = provenance, colour = provenance)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3, shape = 18) +
 scale_x_discrete(breaks = seq(11, 79, by = 2))

ggplot(data = big_table_long, aes(x = as.factor(age), y = seOfmean, group = provenance, colour = provenance)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3, shape = 18) +
 scale_x_discrete(breaks = seq(11, 79, by = 2))


```

# over 18
```{r}
census_school_type <- readxl::read_excel("../data/729305_Zensus2011_Bildung_Schulform.xlsx", 
    sheet = "Migration und Schulform") 

census_school_type <- census_school_type %>% 
  # remove redundant columns of higher at school categories (e.g., Deutsche mit Migrationshintergrund)
  select(1:2, 21:28, 45:60, 69:76, 85:100) %>%
  # exclude sex and age columns
  select(3:50) %>%
  # before iteratively naming the 48 columns, 8 (school types) * 6 (migration background) 
  set_names(map(c("no mig background", 
                  "foreigner, own mig background", 
                  "foreigner, no own mig background", 
                  "citizen, own mig background",
                  "citizen, mig background from both parents",
                  "citizen, mig background from one parent"),
                ~ paste0(.x, "_", c("total", 
                                    "level 0: no longer at school", # Entfällt, da kein/e Schüler/-innen
                                    "level 1: primary", # Grundschule
                                    "level 2a: lower secondary", # Hauptschule
                                    "level 3b: upper secondary, vocational", # Realschule
                                    "level 3a: upper secondary, general", # Gymnasium
                                    "level 0: comprehensive school", # Gesamtschule
                                    "level 0: other school"))) %>% # Sonstige Schule
            unlist()) %>%
  mutate(age = as.numeric(parse_number(census_school_type[[2]])),
         male = census_school_type[[1]],
         ) %>% 
  relocate(c(age,male)) %>% 
  mutate(male = ifelse(row_number() >= 115 & row_number() <= 215, TRUE, FALSE)) %>% 
  slice(-(1:113), -215) %>% 
  pivot_longer(cols = 3:50,
               names_to = c("mig", "school_type"),
               names_sep = "_",
               values_to = "census_n") %>%
  mutate(census_n = ifelse(census_n == "/", 0, as.numeric(census_n)))



census_ISCED <- readxl::read_excel("../data/729305_Zensus2011_Bildung_ISCED.xlsx", sheet = "Migration und ISCED")

census_ISCED <- census_ISCED %>% 
  set_names(paste0("var", 1:133)) %>% 
  select(-(
    census_ISCED %>% 
    summarise(across(everything(), ~ any(str_detect(., "ISCED-Ebene")) & any(str_detect(., "Insgesamt")))) %>% 
    unlist() %>% 
    which()
  )) %>% 
  select(1:2, var24:var34, var57:var78, var90:var100, var112:var133) %>% 
  select(3:56) %>%
  set_names(map(c("no mig background", 
                  "foreigner, own mig background", 
                  "foreigner, no own mig background", 
                  "citizen, own mig background",
                  "citizen, mig background from both parents",
                  "citizen, mig background from one parent"),
                ~ paste0(.x, "_", c("total",
                                    "level 1: primary",                                
                                    "level 2a: lower secondary",                             
                                    "level 3a: upper secondary, general",                               
                                    "level 3b: upper secondary, vocational",                               
                                    "level 4a: post-secondary",                               
                                    "level 5a: tertiary, college etc.",                               
                                    "level 5b: tertiary, tech school etc.",                               
                                    "level 6: PhD"))) %>% 
            unlist()) %>% 
  mutate(age = as.numeric(parse_number(census_ISCED[[2]])),
         male = census_ISCED[[1]]) %>% 
  relocate(c(age,male)) %>% 
  mutate(male = ifelse(row_number() >= 99 & row_number() <= 186, TRUE, FALSE)) %>% 
  slice(-(1:99), -186) %>% 
  pivot_longer(cols = 3:56,
               names_to = c("mig", "isced"),
               names_sep = "_",
               values_to = "census_n") %>%
  mutate(census_n = ifelse(census_n == "/", 0, as.numeric(census_n)))


# 11 because that's the minimum age for the educ and mig variables we used
census_school_type_11_18 <- census_school_type %>% 
  filter((age >= 11 & age <= 18) & school_type != "total") %>% 
  rename(educ = "school_type") %>% 
  relocate(educ, .after = "mig")


census_ISCED_19_79 <- census_ISCED %>% 
  filter((age >= 19 & age <= 79) & isced != "total") %>% 
  rename(educ = "isced")

census18 <- census_school_type_11_18 %>% 
  bind_rows(census_ISCED_19_79) %>%
  mutate(over_18 = ifelse(age > 18, T, F))




library(tidyverse)
library(brms)
options(mc.cores = 4, 
        brms.backend = "cmdstanr",
        scipen = 999,
        digits = 4)
load("../data/tl_clean.Rda")
tl_no_1st_twins18 <- tlperson  %>% 
  filter(ptyp == 300 | ptyp == 400) %>% 
  pivot_wider(id_cols = fid, names_from = ptyp, values_from = mig2000) %>% 
  right_join(tlperson, by = "fid") %>% 
  rename(mig2000_dad = `400`, mig2000_mom = `300`) %>% 
  mutate(mig2000_dad = as.numeric(ifelse(ptyp == 300 | ptyp == 400, NA_character_, mig2000_dad)),
         mig2000_mom = as.numeric(ifelse(ptyp == 300 | ptyp == 400, NA_character_, mig2000_mom)),
         mig0300 = recode(as.numeric(mig0300), `2` = 1),
         mig0400 = recode(as.numeric(mig0400), `2` = 1),
         mig0520 = coalesce(mig0520, 1),
         age = age0101/12,
         male = sex == 1,
         eca0108 = str_sub(as.character(as_factor(eca0108)), 4, -1),
         born_abroad = case_when(
            mig2000 != 1 ~ 'self',
            mig2000 == 1 & ((coalesce(mig2000_dad, mig0400) == 1 & coalesce(mig2000_mom, mig0300) == 1)) ~ 'none',
            coalesce(mig2000_dad, mig0400) != 1 & coalesce(mig2000_mom, mig0300) != 1 ~ 'both_parents',
            mig2000_mom != 1 ~ 'one_parent',
            mig2000_dad != 1 ~ 'one_parent',  
            mig0300 != 1 ~ 'one_parent',
            mig0400 != 1 ~ 'one_parent',
            mig2000 == 1 ~ 'none',
            TRUE ~ "none"), 
         mig = case_when(
            born_abroad == "self" & mig0520 == 1 ~ "citizen, own mig background",
            born_abroad == "self" & mig0520 != 1 ~ "foreigner, own mig background",
            born_abroad != "self" & mig0520 != 1 ~ "foreigner, no own mig background",
            born_abroad == "one_parent" & mig0520 == 1 ~ "citizen, mig background from one parent",
            born_abroad == "both_parents" & mig0520 == 1 ~ "citizen, mig background from both parents",
            born_abroad == "none" & mig0520 == 1 ~ "no mig background"),
         school_type = case_when(
            edu0400 == 1 ~ "level 1: primary", # Grundschule
            edu0400 == 2 ~ "level 1: primary", # Orientierungsschule
            edu0400 == 3 ~ "level 2a: lower secondary", # Hauptschule
            edu0400 == 4 ~ "level 3b: upper secondary, vocational", # Realschule
            edu0400 == 5 ~ "level 0: comprehensive school", # Verbundene Haupt- und Realschule (auch Sekundar-, Real-, Regel-, Mittel-, Ober- und Wirtschaftsschule, regionale Schule, erweiterte Realschule)
            edu0400 == 6 ~ "level 0: comprehensive school", # Gesamtschule
            edu0400 == 7 ~ "level 0: comprehensive school", # Waldorfschule
            edu0400 == 8 ~ "level 3a: upper secondary, general", # Gymnasium (auch Kolleg)
            edu0400 == 9 ~ "level 0: other school", # Sonderschule/Förderschule
            edu0400 == 10 ~ "level 0: other school", # Andere Schule
            edu0100 == 3 ~ "level 0: not at school"), # "ich gehe nicht mehr in die Schule"
         isced = case_when(
            eca0108 == "3] -83: in school or training/not in school yet" ~ "level 1: primary",
            eca0108 == "9] -89: not codable" ~ NA_character_,
            eca0108 == "5] -95: doesn't apply (screened out)" ~ NA_character_,
            eca0108 == "level 1" ~ "level 1: primary",
            eca0108 == "level 2a" ~ "level 2a: lower secondary",
            eca0108 == "level 3a" ~ "level 3a: upper secondary, general",
            eca0108 == "level 3b" ~ "level 3b: upper secondary, vocational",
            eca0108 == "level 3c" ~ "level 3b: upper secondary, vocational",
            eca0108 == "level 4a" ~ "level 4a: post-secondary",
            eca0108 == "level 5a" ~ "level 5a: tertiary, college etc.",
            eca0108 == " level 5b" ~ "level 5b: tertiary, tech school etc.",
            eca0108 == " level 6" ~ "level 6: PhD"),
    educ = as.factor(ifelse(age0100 <= 18, school_type, isced)),
    educ = relevel(educ, 7),
    isced = relevel(as.factor(isced), 4),
    over_18 = ifelse(age0100 > 18, T, F)) %>%
 filter(!is.na(cft_total) & !is.na(educ)  
         & ptyp != 1) # !is.na(educ) removes 272 rows, kids at school age who don't have a school type for some reason

brm_age_by_educ_over_18_in_by <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ:over_18) + (1 | male:educ:over_18) + (1 | mig:educ:male:over_18) + s(age, by = interaction(educ, over_18)),
      sigma ~ (1 | mig) + (1 | educ:over_18) + (male)  + (1 | mig:male) + (1 | mig:educ:over_18) + (1 | male:educ:over_18) + (1 | mig:educ:male:over_18) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_over_18_in_by",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")



brm_age_by_educ_over_18 <-
  brm(bf(
      cft_total ~ (1 | mig)  + (male)  + (1 | mig:male) + (1 | mig:educ:over_18) + (1 | male:educ:over_18) + (1 | mig:educ:male:over_18) + s(age, by = educ),
      sigma ~ (1 | mig) + (1 | educ:over_18) + (male)  + (1 | mig:male) + (1 | mig:educ:over_18) + (1 | male:educ:over_18) + (1 | mig:educ:male:over_18) + s(age)),
      chains = 4,
      iter = 2000,
      family = gaussian(),
      seed = 810,
      file = "../brms/model_selection_FINAL!!!/brm_age_by_educ_over_18",
      file_refit = "never",
      data = tl_no_1st_twins18) %>%
  add_criterion("loo")
brm_age_by_educ_over_18 
brm_age_by_educ_over_18_in_by 
```